#!/usr/bin/env bash
# dcli integration functions for donarch installer

# Source utils for logging
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/utils.sh"

# Check if dcli should be installed
prompt_dcli_installation() {
    log_step "dcli Integration (Optional)"

    cat << 'EOF'
dcli is a declarative package management tool for Arch Linux.
It allows you to:
  • Manage all your packages in YAML configuration files
  • Track your system configuration in git
  • Sync your setup across multiple machines
  • Organize packages into reusable modules

If you install dcli, this installer will automatically:
  • Install dcli-arch-git from AUR
  • Create dcli configuration structure
  • Add all bd-configs packages to your dcli host.yaml
  • Set up modules for Hyprland and Niri

You can manage your system declaratively with dcli after installation.

EOF

    if prompt_yes_no "Would you like to install and configure dcli?" "n"; then
        return 0
    else
        return 1
    fi
}

# Install dcli package
install_dcli() {
    log_step "Installing dcli"

    log_info "Installing dcli-arch-git from AUR..."
    $AUR_HELPER -S --needed --noconfirm dcli-arch-git

    if [ $? -eq 0 ]; then
        log_success "dcli installed successfully"
        return 0
    else
        log_error "Failed to install dcli"
        return 1
    fi
}

# Initialize dcli configuration structure
init_dcli_config() {
    local user_name="$1"
    local config_dir="/home/$user_name/.config/arch-config"

    log_info "Initializing dcli configuration structure..."

    # Create directory structure
    mkdir -p "$config_dir"/{hosts,modules,scripts,state}

    # Create config.yaml pointer file
    local hostname=$(hostname)
    cat > "$config_dir/config.yaml" << EOF
# dcli configuration pointer
# This file points to your active host configuration
host: $hostname
EOF

    log_success "dcli configuration structure created"
}

# Create dcli host.yaml with all bd-configs packages
create_dcli_host_config() {
    local user_name="$1"
    local repo_dir="$2"
    local install_hyprland="$3"
    local install_niri="$4"
    local optional_apps=("${@:5}")

    local hostname=$(hostname)
    local config_dir="/home/$user_name/.config/arch-config"
    local host_file="$config_dir/hosts/$hostname.yaml"

    log_info "Creating dcli host configuration for $hostname..."

    # Start building the host.yaml file
    cat > "$host_file" << EOF
# dcli host configuration for $hostname
# Generated by donarch installer
# https://gitlab.com/theblackdon/donarch

host: $hostname
description: BD-Configs desktop with DankMaterialShell

# Enable compositor modules
enabled_modules:
  - base
  - themes
  - dms
  - apps
EOF

    # Add compositor modules based on selection
    if [ "$install_hyprland" = "true" ]; then
        echo "  - hyprland" >> "$host_file"
    fi

    if [ "$install_niri" = "true" ]; then
        echo "  - niri" >> "$host_file"
    fi

    # Add optional apps if any
    if [ ${#optional_apps[@]} -gt 0 ]; then
        echo "" >> "$host_file"
        echo "# Optional applications" >> "$host_file"
        echo "packages:" >> "$host_file"
        for app in "${optional_apps[@]}"; do
            echo "  - $app" >> "$host_file"
        done
    fi

    # Add settings
    cat >> "$host_file" << EOF

# dcli settings
flatpak_scope: user
auto_prune: false
aur_helper: ${AUR_HELPER:-paru}
editor: nano

# Configuration backup settings
config_backups:
  enabled: true
  max_backups: 5

# System backup settings (requires timeshift or snapper)
system_backups:
  enabled: false
  backup_on_sync: false
  backup_on_update: false
EOF

    log_success "Host configuration created at $host_file"
}

# Create dcli base module
create_base_module() {
    local user_name="$1"
    local repo_dir="$2"
    local config_dir="/home/$user_name/.config/arch-config"
    local module_file="$config_dir/modules/base.yaml"

    log_info "Creating base module..."

    cat > "$module_file" << 'EOF'
# Base packages for all DonArch systems
description: Core dependencies and build tools

packages:
  # Build essentials
  - git
  - cmake
  - meson
  - cpio
  - gcc
  - base-devel

  # Utilities
  - jq
  - dialog
EOF

    log_success "Base module created"
}

# Create dcli themes module
create_themes_module() {
    local user_name="$1"
    local repo_dir="$2"
    local config_dir="/home/$user_name/.config/arch-config"
    local module_file="$config_dir/modules/themes.yaml"

    log_info "Creating themes module..."

    cat > "$module_file" << 'EOF'
# Catppuccin Mocha theme packages
description: Catppuccin Mocha theme for GTK, Qt, icons, and cursors

packages:
  # Qt Wayland support
  - qt5-wayland
  - qt6-wayland
  - qt5ct
  - qt6ct

  # GTK
  - gtk3
  - gtk4

  # Themes and icons
  - catppuccin-gtk-theme-mocha
  - tela-icon-theme-purple-git
  - bibata-cursor-theme-bin
  - kvantum-theme-catppuccin-git
  - matugen
EOF

    log_success "Themes module created"
}

# Create dcli shell module (noctalia or dms)
create_shell_module() {
    local user_name="$1"
    local repo_dir="$2"
    local selected_shell="${3:-noctalia}"
    local config_dir="/home/$user_name/.config/arch-config"
    local module_file="$config_dir/modules/dms.yaml"

    if [ "$selected_shell" = "noctalia" ]; then
        log_info "Creating Noctalia shell module..."
        cat > "$module_file" << 'EOF'
# Noctalia Shell and display manager
description: Noctalia Shell with ly

packages:
  - noctalia-shell
  - quickshell
  - ly
EOF
    else
        log_info "Creating DMS module..."
        cat > "$module_file" << 'EOF'
# DankMaterialShell and display manager
description: DankMaterialShell with ly

packages:
  - dms-shell-git
  - quickshell
  - ly
EOF
    fi

    log_success "Shell module created"
}

# Create dcli apps module
create_apps_module() {
    local user_name="$1"
    local repo_dir="$2"
    local config_dir="/home/$user_name/.config/arch-config"
    local module_file="$config_dir/modules/apps.yaml"

    log_info "Creating apps module..."

    cat > "$module_file" << 'EOF'
# Required applications
description: Essential applications (terminal, file manager, shell)

packages:
  - kitty
  - nemo
  - fish
  - fastfetch
EOF

    log_success "Apps module created"
}

# Create dcli Hyprland module
create_hyprland_module() {
    local user_name="$1"
    local repo_dir="$2"
    local config_dir="/home/$user_name/.config/arch-config"
    local module_file="$config_dir/modules/hyprland.yaml"

    log_info "Creating Hyprland module..."

    cat > "$module_file" << 'EOF'
# Hyprland compositor and utilities
description: Hyprland dynamic tiling Wayland compositor

packages:
  - hyprland
  - hypridle
  - xdg-desktop-portal-hyprland
  - xdg-desktop-portal-gtk
  - wl-clipboard
  - grimblast-git
  - grim
  - slurp
  - nwg-displays
  - brightnessctl
  - pavucontrol
  - network-manager-applet
EOF

    log_success "Hyprland module created"
}

# Create dcli Niri module
create_niri_module() {
    local user_name="$1"
    local repo_dir="$2"
    local config_dir="/home/$user_name/.config/arch-config"
    local module_file="$config_dir/modules/niri.yaml"

    log_info "Creating Niri module..."

    cat > "$module_file" << 'EOF'
# Niri compositor and utilities
description: Niri scrollable-tiling Wayland compositor

packages:
  - niri
  - xdg-desktop-portal-gnome
  - wl-clipboard
  - wl-clip-persist
  - cliphist
  - grim
  - slurp
  - satty
  - swaybg
  - brightnessctl
  - fuzzel
  - mako
  - waybar
  - sway-audio-idle-inhibit-git
  - swayidle
EOF

    log_success "Niri module created"
}



# Set proper ownership for dcli config
fix_dcli_ownership() {
    local user_name="$1"
    local config_dir="/home/$user_name/.config/arch-config"

    log_info "Setting proper ownership for dcli configuration..."
    sudo chown -R "$user_name:$user_name" "$config_dir"
    log_success "Ownership set correctly"
}

# Main dcli setup function
setup_dcli() {
    local user_name="$1"
    local repo_dir="$2"
    local install_hyprland="$3"
    local install_niri="$4"
    local selected_shell="${5:-noctalia}"
    shift 5
    local optional_apps=("$@")

    log_step "Setting up dcli"

    # Install dcli
    install_dcli || return 1

    # Initialize configuration structure
    init_dcli_config "$user_name"

    # Create all modules
    create_base_module "$user_name" "$repo_dir"
    create_themes_module "$user_name" "$repo_dir"
    create_shell_module "$user_name" "$repo_dir" "$selected_shell"
    create_apps_module "$user_name" "$repo_dir"

    # Create compositor modules based on selection
    if [ "$install_hyprland" = "true" ]; then
        create_hyprland_module "$user_name" "$repo_dir"
    fi

    if [ "$install_niri" = "true" ]; then
        create_niri_module "$user_name" "$repo_dir"
    fi

    # Create host configuration
    create_dcli_host_config "$user_name" "$repo_dir" "$install_hyprland" "$install_niri" "${optional_apps[@]}"

    # Fix ownership
    fix_dcli_ownership "$user_name"

    log_success "dcli setup complete!"
    echo ""
    log_info "dcli has been configured with all donarch packages"
    log_info "Configuration location: ~/.config/arch-config"
    echo ""
    log_info "Useful dcli commands:"
    echo "  dcli status        - View current configuration"
    echo "  dcli sync          - Sync packages with configuration"
    echo "  dcli module list   - List all modules"
    echo "  dcli edit          - Edit configuration files"
    echo "  dcli repo init     - Initialize git repo (recommended)"
    echo ""

    return 0
}
